server:
  port: 8888
#spring:
#  profiles:
#    active: native

spring.application.name: ConfigServer
spring.profiles.active: default
spring.cloud.config.server:
  git:
    uri: https://github.com/sundeepk1/config-repo
    search-paths:
      - 'config/*service'
      - 'config'
      - 'config/*service/*'
      - 'config/*service/*/*'
    skipSslValidation: true
    force-pull: true
    default-label: main
#   timeout: 180
#  profiles:
#    active: default

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always