server.port: 8888
logging.file: configserver.log
spring.application.name: ConfigServer
spring.profiles.active: default
spring.cloud.config.server:
  git:
    uri: https://github.com/sundeepk1/config-repo
    search-paths:
      - 'config/*service'
      - 'config'
      - 'config/*service/*'
      - 'config/*service/*/*'
      - 'common,{application}'
    skipSslValidation: true
    force-pull: true
    default-label: main
    ignoreLocalSshSettings: true
    strictHostKeyChecking: false
    cloneOnStart: true
    timeout: 60
  health:
    repositories:
      ConfigServer:
        label: master
        name: 'ConfigServer'
        profiles: default
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: false
    health.show-details: always
